
import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import localFont from "next/font/local";
import "./globals.css";
import Header from "../../Header/Header";
import Footer from "../../Footer/Footer";
import Headline from "../../Headline/Headline";

const roboto = Roboto({
  weight: ["400","700"],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className}  antialiased`}
        >
          <Headline/>
          <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
